<?php

/* * ***************************************************************************

  Ghi chú:hoàn thành ngày 29-07-2015
  Copyright :Hồ Minh Trí

 * ************************************************************************** */

if(!defined('BASEPATH'))
	exit('No direct script access allowed');

$config=array(
	//Login Admin
	'login/index'=>array(
		array(
			'field'=>'login_account',
			'label'=>'lang:error_admin_account',
			'rules'=>'required|custom_account'
		),
		array(
			'field'=>'login_password',
			'label'=>'lang:error_admin_pass',
			'rules'=>'required|custom_pass'
		),
		array(
			'field'=>'login_language',
			'label'=>'',
			'rules'=>''
		)
	),
	//Add Admin Menu
	'add_update_menu_admin'=>array(
		array(
			'field'=>'txt_menu_class',
			'label'=>'lang:error_admin_require',
			'rules'=>'required'
		),
		array(
			'field'=>'txt_menu_name_vi',
			'label'=>'lang:error_admin_require',
			'rules'=>'required'
		),
		array(
			'field'=>'txt_menu_name_en',
			'label'=>'lang:error_admin_require',
			'rules'=>'required'
		),
		array(
			'field'=>'txt_menu_order',
			'label'=>'lang:custom_only_number',
			'rules'=>'required|custom_onlyNumber'
		),
		array(
			'field'=>'txt_menu_public',
			'label'=>'',
			'rules'=>''
		),
		array(
			'field'=>'txt_menu_cateogry',
			'label'=>'',
			'rules'=>''
		)
	),
	//Add User
	'add_user'=>array(
		array(
			'field'=>'txt_user_account',
			'label'=>'lang:error_admin_account_register',
			'rules'=>'required|custom_account|callback_check_user_account1'
		),
		array(
			'field'=>'txt_user_pass',
			'label'=>'lang:error_admin_pass',
			'rules'=>'required|custom_pass'
		),
		array(
			'field'=>'txt_confirm_user_pass',
			'label'=>'lang:error_admin_confirm_pass',
			'rules'=>'required|matches[txt_user_pass]'
		),
		array(
			'field'=>'txt_email',
			'label'=>'lang:error_admin_email',
			'rules'=>'required|valid_email'
		),
		array(
			'field'=>'txt_user_name',
			'label'=>'lang:error_admin_user_name',
			'rules'=>'required|custom_alpha_dash'
		),
		array(
			'field'=>'txt_user_birthday',
			'label'=>'lang:error_admin_date',
			'rules'=>'required|custom_date'
		),
		array(
			'field'=>'txt_user_address',
			'label'=>'lang:error_admin_require',
			'rules'=>'required'
		),
		array(
			'field'=>'txt_user_phone',
			'label'=>'lang:error_admin_phone',
			'rules'=>'required|custom_phone'
		),
		array(
			'field'=>'txt_user_fax',
			'label'=>'lang:custom_only_number',
			'rules'=>'custom_onlyNumber'
		),
		array(
			'field'=>'txt_user_directory',
			'label'=>'',
			'rules'=>''
		),
		array(
			'field'=>'txt_user_gender',
			'label'=>'',
			'rules'=>''
		),
		array(
			'field'=>'txt_user_img',
			'label'=>'',
			'rules'=>''
		),
		array(
			'field'=>'txt_user_web',
			'label'=>'',
			'rules'=>''
		)
	),
	//Update User
	'update_user'=>array(
		array(
			'field'=>'txt_user_account',
			'label'=>'lang:error_admin_account_register',
			'rules'=>'required|custom_account'
		),
		array(
			'field'=>'txt_user_pass',
			'label'=>'lang:error_admin_pass',
			'rules'=>'custom_pass'
		),
		array(
			'field'=>'txt_confirm_user_pass',
			'label'=>'lang:error_admin_confirm_pass',
			'rules'=>'matches[txt_user_pass]'
		),
		array(
			'field'=>'txt_email',
			'label'=>'lang:error_admin_email',
			'rules'=>'required|valid_email'
		),
		array(
			'field'=>'txt_user_name',
			'label'=>'lang:error_admin_user_name',
			'rules'=>'required|custom_alpha_dash'
		),
		array(
			'field'=>'txt_user_birthday',
			'label'=>'lang:error_admin_date',
			'rules'=>'required|custom_date'
		),
		array(
			'field'=>'txt_user_address',
			'label'=>'lang:error_admin_require',
			'rules'=>'required'
		),
		array(
			'field'=>'txt_user_phone',
			'label'=>'lang:error_admin_phone',
			'rules'=>'required|custom_phone'
		),
		array(
			'field'=>'txt_user_fax',
			'label'=>'lang:custom_only_number',
			'rules'=>'custom_onlyNumber'
		),
		array(
			'field'=>'txt_user_directory',
			'label'=>'',
			'rules'=>''
		),
		array(
			'field'=>'txt_user_gender',
			'label'=>'',
			'rules'=>''
		),
		array(
			'field'=>'txt_user_img',
			'label'=>'',
			'rules'=>''
		),
		array(
			'field'=>'txt_user_web',
			'label'=>'',
			'rules'=>''
		)
	),
	//Add Update User Group
	'add_update_user_group'=>array(
		array(
			'field'=>'txt_user_group_name',
			'label'=>'lang:error_admin_user_group_name',
			'rules'=>'custom_alpha_dash'
		)
	),
	//Add Update Facebook
	'add_update_facebook'=>array(
		array(
			'field'=>'txt_facebook_name',
			'label'=>'lang:error_admin_require',
			'rules'=>'required'
		),
		array(
			'field'=>'txt_facebook_user',
			'label'=>'lang:error_admin_account_register',
			'rules'=>'required|custom_account|callback_check_user_account1_exist'
		),
		array(
			'field'=>'txt_facebook_theme',
			'label'=>'lang:error_admin_custom_select',
			'rules'=>'custom_select'
		),
		array(
			'field'=>'txt_facebook_public',
			'label'=>'',
			'rules'=>''
		),
		array(
			'field'=>'txt_facebook_order',
			'label'=>'lang:custom_only_number',
			'rules'=>'required|custom_onlyNumber'
		),
		array(
			'field'=>'txt_facebook_post_bool',
			'label'=>'',
			'rules'=>''
		),
		array(
			'field'=>'txt_facebook_post_message',
			'label'=>'',
			'rules'=>''
		),
		array(
			'field'=>'txt_facebook_post_url',
			'label'=>'',
			'rules'=>''
		),
		array(
			'field'=>'txt_facebook_post_title',
			'label'=>'',
			'rules'=>''
		),
		array(
			'field'=>'txt_facebook_post_summary',
			'label'=>'',
			'rules'=>''
		),
		array(
			'field'=>'txt_facebook_post_image',
			'label'=>'',
			'rules'=>''
		),
		array(
			'field'=>'txt_facebook_friend_bool',
			'label'=>'',
			'rules'=>''
		),
		array(
			'field'=>'txt_facebook_friend_id',
			'label'=>'',
			'rules'=>''
		),
		array(
			'field'=>'txt_facebook_friend_message',
			'label'=>'',
			'rules'=>''
		),
		array(
			'field'=>'txt_facebook_friend_url',
			'label'=>'',
			'rules'=>''
		),
		array(
			'field'=>'txt_facebook_friend_title',
			'label'=>'',
			'rules'=>''
		),
		array(
			'field'=>'txt_facebook_friend_summary',
			'label'=>'',
			'rules'=>''
		),
		array(
			'field'=>'txt_facebook_friend_image',
			'label'=>'',
			'rules'=>''
		),
		array(
			'field'=>'txt_facebook_comment_bool',
			'label'=>'',
			'rules'=>''
		),
		array(
			'field'=>'txt_facebook_comment_id',
			'label'=>'',
			'rules'=>''
		),
		array(
			'field'=>'txt_facebook_comment_message',
			'label'=>'',
			'rules'=>''
		),
		array(
			'field'=>'txt_facebook_like_bool',
			'label'=>'',
			'rules'=>''
		),
		array(
			'field'=>'txt_facebook_like_id',
			'label'=>'',
			'rules'=>''
		)
	),
	//Add Update Category Sub
	'add_update_category_sub'=>array(
		array(
			'field'=>'txt_cate_name',
			'label'=>'lang:error_admin_require',
			'rules'=>'required'
		),
		array(
			'field'=>'txt_cate_alias',
			'label'=>'lang:error_admin_require',
			'rules'=>'required'
		),
		array(
			'field'=>'txt_cate_order',
			'label'=>'lang:custom_only_number',
			'rules'=>'required|custom_onlyNumber'
		),
		array(
			'field'=>'txt_category_sub',
			'label'=>'',
			'rules'=>''
		),
		array(
			'field'=>'txt_cate_public',
			'label'=>'',
			'rules'=>''
		)
	),
	//Add Update Category Product
	'add_update_category_product'=>array(
		array(
			'field'=>'txt_cate_name',
			'label'=>'lang:error_admin_require',
			'rules'=>'required'
		),
		array(
			'field'=>'txt_cate_alias',
			'label'=>'lang:error_admin_require',
			'rules'=>'required'
		),
		array(
			'field'=>'txt_cate_order',
			'label'=>'lang:custom_only_number',
			'rules'=>'required|custom_onlyNumber'
		),
		array(
			'field'=>'txt_category_product',
			'label'=>'',
			'rules'=>''
		),
		array(
			'field'=>'txt_cate_img',
			'label'=>'',
			'rules'=>''
		),
		array(
			'field'=>'txt_cate_public',
			'label'=>'',
			'rules'=>''
		),
		array(
			'field'=>'txt_cate_seo_keyword',
			'label'=>'',
			'rules'=>''
		),
		array(
			'field'=>'txt_cate_seo_description',
			'label'=>'',
			'rules'=>''
		)
	),
	//Add Update Category News
	'add_update_category_news'=>array(
		array(
			'field'=>'txt_cate_name',
			'label'=>'lang:error_admin_require',
			'rules'=>'required'
		),
		array(
			'field'=>'txt_cate_alias',
			'label'=>'lang:error_admin_require',
			'rules'=>'required'
		),
		array(
			'field'=>'txt_cate_order',
			'label'=>'lang:custom_only_number',
			'rules'=>'required|custom_onlyNumber'
		),
		array(
			'field'=>'txt_category_news',
			'label'=>'',
			'rules'=>''
		),
		array(
			'field'=>'txt_cate_img',
			'label'=>'',
			'rules'=>''
		),
		array(
			'field'=>'txt_cate_public',
			'label'=>'',
			'rules'=>''
		),
		array(
			'field'=>'txt_cate_seo_keyword',
			'label'=>'',
			'rules'=>''
		),
		array(
			'field'=>'txt_cate_seo_description',
			'label'=>'',
			'rules'=>''
		)
	),
	//Add Product
	'add_product'=>array(
		array(
			'field'=>'txt_product_id',
			'label'=>'lang:error_admin_product_id',
			'rules'=>'required|alpha_dash|callback_check_product_id1'
		),
		array(
			'field'=>'txt_product_name',
			'label'=>'lang:error_admin_require',
			'rules'=>'required'
		),
		array(
			'field'=>'txt_product_alias',
			'label'=>'lang:error_admin_require',
			'rules'=>'required'
		),
		array(
			'field'=>'txt_product_price',
			'label'=>'lang:custom_only_number',
			'rules'=>'required|custom_onlyNumber_format'
		),
		array(
			'field'=>'txt_product_price_old',
			'label'=>'lang:custom_only_number',
			'rules'=>'required|custom_onlyNumber_format'
		),
		array(
			'field'=>'txt_product_number',
			'label'=>'lang:custom_only_number',
			'rules'=>'required|custom_onlyNumber_format'
		),
		array(
			'field'=>'txt_cate_product',
			'label'=>'lang:error_admin_custom_select',
			'rules'=>'custom_select'
		),
		array(
			'field'=>'txt_product_order',
			'label'=>'lang:custom_only_number',
			'rules'=>'required|custom_onlyNumber'
		),
		array(
			'field'=>'txt_product_color',
			'label'=>'',
			'rules'=>''
		),
		array(
			'field'=>'txt_product_prominent',
			'label'=>'',
			'rules'=>''
		),
		array(
			'field'=>'txt_product_public',
			'label'=>'',
			'rules'=>''
		),
		array(
			'field'=>'txt_product_seo_keyword',
			'label'=>'',
			'rules'=>''
		),
		array(
			'field'=>'txt_product_seo_description',
			'label'=>'',
			'rules'=>''
		),
		array(
			'field'=>'txt_product_partner',
			'label'=>'',
			'rules'=>''
		),
		array(
			'field'=>'txt_product_application[]',
			'label'=>'',
			'rules'=>''
		),
		array(
			'field'=>'ajax_pattern_product_headline',
			'label'=>'',
			'rules'=>''
		),
		array(
			'field'=>'ajax_pattern_product_content',
			'label'=>'',
			'rules'=>''
		),
		array(
			'field'=>'txt_product_headline_ckeditor',
			'label'=>'',
			'rules'=>''
		),
		array(
			'field'=>'txt_product_content_ckeditor',
			'label'=>'',
			'rules'=>''
		)
	),
	//Update Product
	'update_product'=>array(
		array(
			'field'=>'txt_product_id',
			'label'=>'lang:error_admin_product_id',
			'rules'=>'required|alpha_dash'
		),
		array(
			'field'=>'txt_product_name',
			'label'=>'lang:error_admin_require',
			'rules'=>'required'
		),
		array(
			'field'=>'txt_product_alias',
			'label'=>'lang:error_admin_require',
			'rules'=>'required'
		),
		array(
			'field'=>'txt_product_price',
			'label'=>'lang:custom_only_number',
			'rules'=>'required|custom_onlyNumber_format'
		),
		array(
			'field'=>'txt_product_price_old',
			'label'=>'lang:custom_only_number',
			'rules'=>'required|custom_onlyNumber_format'
		),
		array(
			'field'=>'txt_product_number',
			'label'=>'lang:custom_only_number',
			'rules'=>'required|custom_onlyNumber_format'
		),
		array(
			'field'=>'txt_cate_product',
			'label'=>'lang:error_admin_custom_select',
			'rules'=>'custom_select'
		),
		array(
			'field'=>'txt_product_order',
			'label'=>'lang:custom_only_number',
			'rules'=>'required|custom_onlyNumber'
		),
		array(
			'field'=>'txt_product_color',
			'label'=>'',
			'rules'=>''
		),
		array(
			'field'=>'txt_product_prominent',
			'label'=>'',
			'rules'=>''
		),
		array(
			'field'=>'txt_product_public',
			'label'=>'',
			'rules'=>''
		),
		array(
			'field'=>'txt_product_seo_keyword',
			'label'=>'',
			'rules'=>''
		),
		array(
			'field'=>'txt_product_seo_description',
			'label'=>'',
			'rules'=>''
		),
		array(
			'field'=>'txt_product_partner',
			'label'=>'',
			'rules'=>''
		),
		array(
			'field'=>'txt_product_application[]',
			'label'=>'',
			'rules'=>''
		),
		array(
			'field'=>'ajax_pattern_product_headline',
			'label'=>'',
			'rules'=>''
		),
		array(
			'field'=>'ajax_pattern_product_content',
			'label'=>'',
			'rules'=>''
		),
		array(
			'field'=>'txt_product_headline_ckeditor',
			'label'=>'',
			'rules'=>''
		),
		array(
			'field'=>'txt_product_content_ckeditor',
			'label'=>'',
			'rules'=>''
		)
	),
	//Add Update Product Pattern
	'add_update_product_pattern'=>array(
		array(
			'field'=>'txt_product_pattern_name',
			'label'=>'lang:error_admin_require',
			'rules'=>'required'
		),
		array(
			'field'=>'txt_product_pattern_order',
			'label'=>'lang:custom_only_number',
			'rules'=>'required|custom_onlyNumber'
		),
		array(
			'field'=>'txt_product_pattern_content',
			'label'=>'',
			'rules'=>''
		)
	),
	//Add Update News
	'add_update_news'=>array(
		array(
			'field'=>'txt_news_name',
			'label'=>'lang:error_admin_require',
			'rules'=>'required'
		),
		array(
			'field'=>'txt_news_alias',
			'label'=>'lang:error_admin_require',
			'rules'=>'required'
		),
		array(
			'field'=>'txt_news_order',
			'label'=>'lang:custom_only_number',
			'rules'=>'required|custom_onlyNumber'
		),
		array(
			'field'=>'txt_cate_news',
			'label'=>'lang:error_admin_custom_select',
			'rules'=>'custom_select'
		),
		array(
			'field'=>'txt_news_img',
			'label'=>'',
			'rules'=>''
		),
		array(
			'field'=>'txt_news_public',
			'label'=>'',
			'rules'=>''
		),
		array(
			'field'=>'txt_news_seo_keyword',
			'label'=>'',
			'rules'=>''
		),
		array(
			'field'=>'txt_news_seo_description',
			'label'=>'',
			'rules'=>''
		),
		array(
			'field'=>'txt_news_headline',
			'label'=>'',
			'rules'=>''
		),
		array(
			'field'=>'txt_news_content',
			'label'=>'',
			'rules'=>''
		)
	),
	//Add Update Advertise
	'add_update_advertise'=>array(
		array(
			'field'=>'txt_cate_advertise',
			'label'=>'lang:error_admin_custom_select',
			'rules'=>'custom_select'
		),
		array(
			'field'=>'txt_ad_name',
			'label'=>'lang:error_admin_require',
			'rules'=>'required'
		),
		array(
			'field'=>'txt_ad_img',
			'label'=>'lang:error_admin_require',
			'rules'=>'required'
		),
		array(
			'field'=>'txt_ad_order',
			'label'=>'lang:custom_only_number',
			'rules'=>'required|custom_onlyNumber'
		),
		array(
			'field'=>'txt_ad_link',
			'label'=>'',
			'rules'=>''
		),
		array(
			'field'=>'txt_ad_active',
			'label'=>'',
			'rules'=>''
		),
		array(
			'field'=>'txt_ad_public',
			'label'=>'',
			'rules'=>''
		)
	),
	//Add Update Video
	'add_update_video'=>array(
		array(
			'field'=>'txt_cate_video',
			'label'=>'lang:error_admin_custom_select',
			'rules'=>'custom_select'
		),
		array(
			'field'=>'txt_video_name',
			'label'=>'lang:error_admin_require',
			'rules'=>'required'
		),
		array(
			'field'=>'txt_video_alias',
			'label'=>'lang:error_admin_require',
			'rules'=>'required'
		),
		array(
			'field'=>'txt_video_file',
			'label'=>'lang:error_admin_require',
			'rules'=>'required'
		),
		array(
			'field'=>'txt_video_order',
			'label'=>'lang:custom_only_number',
			'rules'=>'required|custom_onlyNumber'
		),
		array(
			'field'=>'txt_video_img',
			'label'=>'',
			'rules'=>''
		),
		array(
			'field'=>'txt_video_description',
			'label'=>'',
			'rules'=>''
		),
		array(
			'field'=>'txt_video_active',
			'label'=>'',
			'rules'=>''
		),
		array(
			'field'=>'txt_video_public',
			'label'=>'',
			'rules'=>''
		)
	),
	//Add Update Order
	'add_update_order'=>array(
		array(
			'field'=>'txt_order_name',
			'label'=>'lang:error_admin_require',
			'rules'=>'required'
		),
		array(
			'field'=>'txt_order_address',
			'label'=>'lang:error_admin_require',
			'rules'=>'required'
		),
		array(
			'field'=>'txt_order_phone',
			'label'=>'lang:error_admin_phone',
			'rules'=>'required|custom_phone'
		),
		array(
			'field'=>'txt_order_email',
			'label'=>'lang:error_admin_email',
			'rules'=>'required|valid_email'
		),
		array(
			'field'=>'txt_cate_order',
			'label'=>'lang:error_admin_custom_select',
			'rules'=>'custom_select'
		),
		array(
			'field'=>'txt_delivery',
			'label'=>'lang:error_admin_custom_select',
			'rules'=>'custom_select'
		),
		array(
			'field'=>'txt_payment',
			'label'=>'lang:error_admin_custom_select',
			'rules'=>'custom_select'
		)
	),
	//Add Update Delivery Method
	'add_update_delivery_method'=>array(
		array(
			'field'=>'txt_delivery_name',
			'label'=>'lang:error_admin_require',
			'rules'=>'required'
		),
		array(
			'field'=>'txt_delivery_cost',
			'label'=>'lang:custom_only_number',
			'rules'=>'required|custom_onlyNumber'
		),
		array(
			'field'=>'txt_delivery_order',
			'label'=>'lang:custom_only_number',
			'rules'=>'required|custom_onlyNumber'
		),
		array(
			'field'=>'txt_delivery_public',
			'label'=>'',
			'rules'=>''
		),
		array(
			'field'=>'txt_delivery_content',
			'label'=>'',
			'rules'=>''
		)
	),
	//Add Update Payment Method
	'add_update_payment_method'=>array(
		array(
			'field'=>'txt_payment_name',
			'label'=>'lang:error_admin_require',
			'rules'=>'required'
		),
		array(
			'field'=>'txt_payment_cost',
			'label'=>'lang:custom_only_number',
			'rules'=>'required|custom_onlyNumber'
		),
		array(
			'field'=>'txt_payment_order',
			'label'=>'lang:custom_only_number',
			'rules'=>'required|custom_onlyNumber'
		),
		array(
			'field'=>'txt_payment_public',
			'label'=>'',
			'rules'=>''
		),
		array(
			'field'=>'txt_payment_content',
			'label'=>'',
			'rules'=>''
		)
	),
	//Site Change
	'site/change'=>array(
		array(
			'field'=>'txt_pass_old',
			'label'=>'lang:error_admin_password',
			'rules'=>'custom_pass|callback_check_username'
		),
		array(
			'field'=>'txt_pass_new',
			'label'=>'lang:error_admin_pass',
			'rules'=>'required|custom_pass'
		),
		array(
			'field'=>'txt_confirm_pass_new',
			'label'=>'lang:error_admin_confirm_pass',
			'rules'=>'matches[txt_pass_new]'
		)
	),
	//Site General Config
	'site/config'=>array(
		array(
			'field'=>'txt_seo_title',
			'label'=>'lang:error_admin_require',
			'rules'=>'required'
		),
		array(
			'field'=>'txt_seo_keyword',
			'label'=>'lang:error_admin_require',
			'rules'=>'required'
		),
		array(
			'field'=>'txt_seo_description',
			'label'=>'lang:error_admin_require',
			'rules'=>'required'
		),
		array(
			'field'=>'txt_product_page',
			'label'=>'lang:custom_only_number',
			'rules'=>'required|custom_onlyNumber'
		),
		array(
			'field'=>'txt_search_product_page',
			'label'=>'lang:custom_only_number',
			'rules'=>'required|custom_onlyNumber'
		),
		array(
			'field'=>'txt_news_page',
			'label'=>'lang:custom_only_number',
			'rules'=>'required|custom_onlyNumber'
		),
		array(
			'field'=>'txt_static_online_virtual',
			'label'=>'lang:custom_only_number',
			'rules'=>'required|custom_onlyNumber'
		),
		array(
			'field'=>'txt_static_count_virtual',
			'label'=>'lang:custom_only_number',
			'rules'=>'required|custom_onlyNumber'
		),
		array(
			'field'=>'txt_facebook_user_id',
			'label'=>'',
			'rules'=>''
		),
		array(
			'field'=>'txt_facebook_fanpage',
			'label'=>'',
			'rules'=>''
		),
		array(
			'field'=>'txt_footer_front_end',
			'label'=>'',
			'rules'=>''
		)
	),
	//Site Config Email
	'site/email'=>array(
		array(
			'field'=>'txt_email_server_smtp',
			'label'=>'lang:error_admin_require',
			'rules'=>'required'
		),
		array(
			'field'=>'txt_email_port_smtp',
			'label'=>'lang:custom_only_number',
			'rules'=>'required|custom_onlyNumber'
		),
		array(
			'field'=>'txt_email_secure_smtp',
			'label'=>'lang:error_admin_require',
			'rules'=>'required'
		),
		array(
			'field'=>'txt_email_debug_smtp',
			'label'=>'lang:custom_only_number',
			'rules'=>'required|custom_onlyNumber'
		),
		array(
			'field'=>'txt_email_your_name',
			'label'=>'lang:error_admin_user_name',
			'rules'=>'required|custom_alpha_dash'
		),
		array(
			'field'=>'txt_email_email_smtp',
			'label'=>'lang:error_admin_email',
			'rules'=>'required|valid_email'
		),
		array(
			'field'=>'txt_email_pass_smtp',
			'label'=>'lang:error_admin_require',
			'rules'=>'required'
		)
	),
	//Add Update Utility
	'add_update_menu'=>array(
		array(
			'field'=>'txt_menu_name',
			'label'=>'lang:error_admin_require',
			'rules'=>'required'
		),
		array(
			'field'=>'txt_menu_url',
			'label'=>'lang:error_admin_require',
			'rules'=>''
		),
		array(
			'field'=>'txt_menu_order',
			'label'=>'lang:custom_only_number',
			'rules'=>'required|custom_onlyNumber'
		),
		array(
			'field'=>'txt_menu_public',
			'label'=>'',
			'rules'=>''
		)
	),
	//Add Update Support
	'add_update_support'=>array(
		array(
			'field'=>'txt_support_type',
			'label'=>'lang:error_admin_custom_select',
			'rules'=>'custom_select'
		),
		array(
			'field'=>'txt_support_name',
			'label'=>'lang:error_admin_support_name',
			'rules'=>'required|custom_alpha_dash'
		),
		array(
			'field'=>'txt_support_order',
			'label'=>'lang:custom_only_number',
			'rules'=>'required|custom_onlyNumber'
		),
		array(
			'field'=>'txt_support_nick',
			'label'=>'lang:error_admin_support_nick',
			'rules'=>'required|callback_check_validation_support_nick'
		),
		array(
			'field'=>'txt_support_public',
			'label'=>'',
			'rules'=>''
		)
	),
	//Add Update Weblink
	'add_update_weblink'=>array(
		array(
			'field'=>'txt_link_name',
			'label'=>'lang:error_admin_require',
			'rules'=>'required'
		),
		array(
			'field'=>'txt_link_url',
			'label'=>'lang:error_admin_require',
			'rules'=>'required'
		),
		array(
			'field'=>'txt_cate_weblink',
			'label'=>'lang:error_admin_custom_select',
			'rules'=>'custom_select'
		),
		array(
			'field'=>'txt_link_order',
			'label'=>'lang:custom_only_number',
			'rules'=>'required|custom_onlyNumber'
		),
		array(
			'field'=>'txt_support_info',
			'label'=>'',
			'rules'=>''
		),
		array(
			'field'=>'txt_link_public',
			'label'=>'',
			'rules'=>''
		)
	),
	//Add Update Application
	'add_update_application'=>array(
		array(
			'field'=>'txt_application_name',
			'label'=>'lang:error_admin_require',
			'rules'=>'required'
		),
		array(
			'field'=>'txt_application_alias',
			'label'=>'lang:error_admin_require',
			'rules'=>'required'
		),
		array(
			'field'=>'txt_application_order',
			'label'=>'lang:custom_only_number',
			'rules'=>'required|custom_onlyNumber'
		),
		array(
			'field'=>'txt_application_public',
			'label'=>'',
			'rules'=>''
		)
	),
	//Add Update Partner
	'add_update_partner'=>array(
		array(
			'field'=>'txt_partner_name',
			'label'=>'lang:error_admin_require',
			'rules'=>'required'
		),
		array(
			'field'=>'txt_partner_alias',
			'label'=>'lang:error_admin_require',
			'rules'=>'required'
		),
		array(
			'field'=>'txt_cate_partner',
			'label'=>'lang:error_admin_custom_select',
			'rules'=>'custom_select'
		),
		array(
			'field'=>'txt_partner_order',
			'label'=>'lang:custom_only_number',
			'rules'=>'required|custom_onlyNumber'
		),
		array(
			'field'=>'txt_partner_url',
			'label'=>'',
			'rules'=>''
		),
		array(
			'field'=>'txt_partner_img',
			'label'=>'',
			'rules'=>''
		),
		array(
			'field'=>'txt_partner_public',
			'label'=>'',
			'rules'=>''
		)
	),
	//Add Update Utility
	'add_update_utility'=>array(
		array(
			'field'=>'txt_utility_name',
			'label'=>'lang:error_admin_require',
			'rules'=>'required'
		),
		array(
			'field'=>'txt_utility_url',
			'label'=>'lang:error_admin_require',
			'rules'=>'required'
		),
		array(
			'field'=>'txt_utility_order',
			'label'=>'lang:custom_only_number',
			'rules'=>'required|custom_onlyNumber'
		),
		array(
			'field'=>'txt_utility_img',
			'label'=>'',
			'rules'=>''
		),
		array(
			'field'=>'txt_utility_public',
			'label'=>'',
			'rules'=>''
		)
	),
	//Add Update Province
	'add_update_province'=>array(
		array(
			'field'=>'txt_province_name',
			'label'=>'lang:error_admin_require',
			'rules'=>'required'
		),
		array(
			'field'=>'txt_province_order',
			'label'=>'lang:custom_only_number',
			'rules'=>'required|custom_onlyNumber'
		),
		array(
			'field'=>'txt_province_public',
			'label'=>'',
			'rules'=>''
		)
	),
	//Add Update District
	'add_update_district'=>array(
		array(
			'field'=>'txt_district_name',
			'label'=>'lang:error_admin_require',
			'rules'=>'required'
		),
		array(
			'field'=>'txt_district_order',
			'label'=>'lang:custom_only_number',
			'rules'=>'required|custom_onlyNumber'
		),
		array(
			'field'=>'txt_province',
			'label'=>'lang:error_admin_custom_select',
			'rules'=>'custom_select'
		),
		array(
			'field'=>'txt_district_public',
			'label'=>'',
			'rules'=>''
		)
	),
	/* -------------------------------Front-end------------------------------------ */







	//Login Front-end
	'member_login'=>array(
		array(
			'field'=>'txt_account_login',
			'label'=>'lang:error_account',
			'rules'=>'required|custom_account'
		),
		array(
			'field'=>'txt_password_login',
			'label'=>'lang:error_pass',
			'rules'=>'required|custom_pass'
		)
	),
	//Add User Front-end
	'member_register'=>array(
		array(
			'field'=>'txt_user_account',
			'label'=>'lang:error_account_register',
			'rules'=>'required|custom_account|callback_check_user_account1'
		),
		array(
			'field'=>'txt_user_pass',
			'label'=>'lang:error_pass',
			'rules'=>'required|custom_pass'
		),
		array(
			'field'=>'txt_confirm_user_pass',
			'label'=>'lang:error_confirm_pass',
			'rules'=>'required|matches[txt_user_pass]'
		),
		array(
			'field'=>'txt_email',
			'label'=>'lang:error_email',
			'rules'=>'required|valid_email'
		),
		array(
			'field'=>'txt_user_name',
			'label'=>'lang:error_user_name',
			'rules'=>'required|custom_alpha_dash'
		),
		array(
			'field'=>'txt_user_birthday',
			'label'=>'lang:error_date',
			'rules'=>'required|custom_date'
		),
		array(
			'field'=>'txt_user_address',
			'label'=>'lang:error_require',
			'rules'=>'required'
		),
		array(
			'field'=>'txt_user_phone',
			'label'=>'lang:error_phone',
			'rules'=>'required|custom_phone'
		),
		array(
			'field'=>'txt_user_fax',
			'label'=>'lang:custom_only_number',
			'rules'=>'custom_onlyNumber'
		),
		array(
			'field'=>'txt_member_register_captcha',
			'label'=>'lang:error_captcha',
			'rules'=>'required|callback_check_captcha'
		),
		array(
			'field'=>'txt_user_gender',
			'label'=>'',
			'rules'=>''
		),
		array(
			'field'=>'txt_user_img',
			'label'=>'',
			'rules'=>''
		),
		array(
			'field'=>'txt_user_web',
			'label'=>'',
			'rules'=>''
		)
	),
	//Update User Front-end
	'member_update'=>array(
		array(
			'field'=>'txt_user_account',
			'label'=>'lang:error_account_register',
			'rules'=>'required|custom_account'
		),
		array(
			'field'=>'txt_user_pass',
			'label'=>'lang:error_pass',
			'rules'=>'custom_pass'
		),
		array(
			'field'=>'txt_confirm_user_pass',
			'label'=>'lang:error_confirm_pass',
			'rules'=>'matches[txt_user_pass]'
		),
		array(
			'field'=>'txt_email',
			'label'=>'lang:error_email',
			'rules'=>'required|valid_email'
		),
		array(
			'field'=>'txt_user_name',
			'label'=>'lang:error_user_name',
			'rules'=>'required|custom_alpha_dash'
		),
		array(
			'field'=>'txt_user_birthday',
			'label'=>'lang:error_date',
			'rules'=>'required|custom_date'
		),
		array(
			'field'=>'txt_user_address',
			'label'=>'lang:error_require',
			'rules'=>'required'
		),
		array(
			'field'=>'txt_user_phone',
			'label'=>'lang:error_phone',
			'rules'=>'required|custom_phone'
		),
		array(
			'field'=>'txt_user_fax',
			'label'=>'lang:custom_only_number',
			'rules'=>'custom_onlyNumber'
		),
		array(
			'field'=>'txt_member_update_captcha',
			'label'=>'lang:error_captcha',
			'rules'=>'required|callback_check_captcha'
		),
		array(
			'field'=>'txt_user_gender',
			'label'=>'',
			'rules'=>''
		),
		array(
			'field'=>'txt_user_img',
			'label'=>'',
			'rules'=>''
		),
		array(
			'field'=>'txt_user_web',
			'label'=>'',
			'rules'=>''
		)
	),
	//Add Membership Front-end
	'membership_register'=>array(
		array(
			'field'=>'txt_membership_email',
			'label'=>'lang:error_email_exist',
			'rules'=>'required|valid_email|callback_check_email'
		),
		array(
			'field'=>'txt_membership_name',
			'label'=>'lang:error_user_name',
			'rules'=>'required|custom_alpha_dash'
		),
		array(
			'field'=>'txt_membership_birthday',
			'label'=>'lang:error_date',
			'rules'=>'required|custom_date'
		),
		array(
			'field'=>'txt_membership_phone',
			'label'=>'lang:error_phone',
			'rules'=>'required|custom_phone'
		),
		array(
			'field'=>'txt_career_category',
			'label'=>'lang:error_custom_select',
			'rules'=>'custom_select'
		),
		array(
			'field'=>'txt_province_category',
			'label'=>'lang:error_custom_select',
			'rules'=>'custom_select'
		),
		array(
			'field'=>'txt_district_category',
			'label'=>'lang:error_custom_select',
			'rules'=>'custom_select'
		),
		array(
			'field'=>'txt_membership_register_captcha',
			'label'=>'lang:error_captcha',
			'rules'=>'required|callback_check_captcha'
		),
		array(
			'field'=>'txt_membership_gender',
			'label'=>'',
			'rules'=>''
		),
		array(
			'field'=>'txt_membership_address',
			'label'=>'lang:error_require',
			'rules'=>''
		)
	),
	// Membership Card Front-end
	'membership_card'=>array(
		array(
			'field'=>'txt_membership_email',
			'label'=>'lang:error_email_exist',
			'rules'=>'required|valid_email|callback_check_email'
		),
		array(
			'field'=>'txt_membership_name',
			'label'=>'lang:error_user_name',
			'rules'=>'required|custom_alpha_dash'
		),
		array(
			'field'=>'txt_membership_birthday',
			'label'=>'lang:error_date',
			'rules'=>'required|custom_date'
		),
		array(
			'field'=>'txt_membership_phone',
			'label'=>'lang:error_phone',
			'rules'=>'required|custom_phone'
		),
		array(
			'field'=>'txt_career_category',
			'label'=>'lang:error_custom_select',
			'rules'=>'custom_select'
		),
		array(
			'field'=>'txt_province_category',
			'label'=>'lang:error_custom_select',
			'rules'=>'custom_select'
		),
		array(
			'field'=>'txt_district_category',
			'label'=>'lang:error_custom_select',
			'rules'=>'custom_select'
		),
		array(
			'field'=>'txt_membership_card_captcha',
			'label'=>'lang:error_captcha',
			'rules'=>'required|callback_check_captcha'
		),
		array(
			'field'=>'txt_membership_gender',
			'label'=>'',
			'rules'=>''
		),
		array(
			'field'=>'txt_membership_address',
			'label'=>'lang:error_require',
			'rules'=>''
		)
	),
	//Add Comment Front-end
	'add_comment_front_end'=>array(
		array(
			'field'=>'txt_comment_name',
			'label'=>'lang:error_require_comment_name',
			'rules'=>'required'
		),
		array(
			'field'=>'txt_comment_email',
			'label'=>'lang:error_comment_email',
			'rules'=>'required|valid_email'
		),
		array(
			'field'=>'txt_comment_title',
			'label'=>'lang:error_require_comment_title',
			'rules'=>'required'
		),
		array(
			'field'=>'txt_comment_captcha',
			'label'=>'lang:error_comment_captcha',
			'rules'=>'required'
		),
		array(
			'field'=>'txt_comment_content',
			'label'=>'lang:error_require_comment_content',
			'rules'=>'required'
		)
	),
	//Contact Front-end
	'submit_contact'=>array(
		array(
			'field'=>'txt_contact_email',
			'label'=>'lang:error_email',
			'rules'=>'required|valid_email'
		),
		array(
			'field'=>'txt_contact_name',
			'label'=>'lang:error_require',
			'rules'=>'required'
		),
		array(
			'field'=>'txt_contact_address',
			'label'=>'lang:error_require',
			'rules'=>'required'
		),
		array(
			'field'=>'txt_contact_phone',
			'label'=>'lang:error_phone',
			'rules'=>'required|custom_phone'
		),
		array(
			'field'=>'txt_contact_header',
			'label'=>'lang:error_require',
			'rules'=>'required'
		),
		array(
			'field'=>'txt_contact_content',
			'label'=>'lang:error_require',
			'rules'=>'required'
		),
		array(
			'field'=>'txt_contact_captcha',
			'label'=>'lang:error_captcha',
			'rules'=>'required|callback_check_captcha'
		),
		array(
			'field'=>'contact_send_me',
			'label'=>'',
			'rules'=>''
		)
	),
	//Service Front-end
	'submit_service'=>array(
		array(
			'field'=>'txt_service_email',
			'label'=>'lang:error_email',
			'rules'=>'required|valid_email'
		),
		array(
			'field'=>'txt_service_name',
			'label'=>'lang:error_require',
			'rules'=>'required'
		),
		array(
			'field'=>'txt_service_address',
			'label'=>'lang:error_require',
			'rules'=>'required'
		),
		array(
			'field'=>'txt_service_phone',
			'label'=>'lang:error_phone',
			'rules'=>'required|custom_phone'
		),
		array(
			'field'=>'txt_service_header',
			'label'=>'lang:error_require',
			'rules'=>'required'
		),
		array(
			'field'=>'txt_service_content',
			'label'=>'lang:error_require',
			'rules'=>'required'
		),
		array(
			'field'=>'txt_service_captcha',
			'label'=>'lang:error_captcha',
			'rules'=>'required|callback_check_captcha'
		),
		array(
			'field'=>'service_send_me',
			'label'=>'',
			'rules'=>''
		)
	),
	//Cart Order Front-end
	'submit_cart_order'=>array(
		array(
			'field'=>'txt_order_email',
			'label'=>'lang:error_email',
			'rules'=>'required|valid_email'
		),
		array(
			'field'=>'txt_order_name',
			'label'=>'lang:error_require',
			'rules'=>'required'
		),
		array(
			'field'=>'txt_order_address',
			'label'=>'lang:error_require',
			'rules'=>'required'
		),
		array(
			'field'=>'txt_order_phone',
			'label'=>'lang:error_phone',
			'rules'=>'required|custom_phone'
		),
		array(
			'field'=>'txt_cart_order_captcha',
			'label'=>'lang:error_captcha',
			'rules'=>'required|callback_check_captcha'
		),
		array(
			'field'=>'txt_order_content',
			'label'=>'',
			'rules'=>''
		),
		array(
			'field'=>'cart_order_send_me',
			'label'=>'',
			'rules'=>''
		)
	),
	//Cart Shopping Front-end
	'submit_cart_method'=>array(
		array(
			'field'=>'txt_order_email',
			'label'=>'lang:error_email',
			'rules'=>'required|valid_email'
		),
		array(
			'field'=>'txt_order_name',
			'label'=>'lang:error_require',
			'rules'=>'required'
		),
		array(
			'field'=>'txt_order_address',
			'label'=>'lang:error_require',
			'rules'=>'required'
		),
		array(
			'field'=>'txt_order_phone',
			'label'=>'lang:error_phone',
			'rules'=>'required|custom_phone'
		),
		array(
			'field'=>'txt_cart_method_captcha',
			'label'=>'lang:error_captcha',
			'rules'=>'required|callback_check_captcha'
		),
		array(
			'field'=>'cart_method_send_me',
			'label'=>'',
			'rules'=>''
		),
		array(
			'field'=>'txt_order_content',
			'label'=>'',
			'rules'=>''
		),
		array(
			'field'=>'txt_delivery_id',
			'label'=>'',
			'rules'=>''
		),
		array(
			'field'=>'txt_payment_id',
			'label'=>'',
			'rules'=>''
		)
	)
);
